import { Suspense } from "react";
import Link from "next/link";

import {CardFilter} from '@/components'
import {ListCourse} from "./_components";

export const metadata = {
  title: 'Course - WEALPY',
  // description: 'Generated by create next app',
}

export default function Course() {
  return (
    <main className="flex-col w-full min-h-screen items-center mx-auto lg:px-20 lg:py-20 2xl:py-24 ">

      <div className="w-full flex flex-col space-y-8 lg:px-16  2xl:px-32 ">

        <div className="hidden lg:flex flex-row place-content-center items-center gap-4 w-full h-auto bg-gray-800 bg-opacity-40 px-4 py-4 rounded-2xl">
          <div className="w-3/6 font-semibold text-white lg:text-sm 2xl:text-base">
            Akses lebih banyak Course & Recording kelas
          </div>
          <div className="w-2/3 flex flex-row place-content-end items-center gap-2">
            <div className="font-medium text-white text-xs">
              Cuman Rp20.000/Bulan. Masih bingung?
              <span>
                <Link href="/" className='ml-1 text-green-500 underline underline-offset-2'>
                  Tanya Minpy
                </Link>
            </span>
            </div>

            <Link href="/membership" className="px-5 py-2 bg-green-500 hover:bg-opacity-90 font-medium text-white text-sm rounded-full cursor-pointer">
              Mulai Bergabung
            </Link>
          </div>
        </div>

        <div className="flex flex-col lg:flex-row space-y-8 lg:space-y-0 lg:space-x-8">
          <div className="w-full lg:w-5/12 2xl:w-4/12 px-6 lg:px-0">
            <Suspense>
              <CardFilter />
            </Suspense>
          </div>
          <div className="w-full lg:flex lg:flex-grow px-6 lg:px-0">
            <Suspense>
              <ListCourse />
            </Suspense>
          </div>
        </div>

      </div>

    </main>
  )
}
