import {Suspense} from 'react';

import {
  Jumbotron, PriceList, WhyChooseUs, ContactUs
} from './_components'

export const metadata = {
  title: 'WEALPY',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className="flex-col w-full min-h-screen items-center justify-between mx-auto px-4 sm:px-10 2xl:px-20">
      <Suspense>
        <Jumbotron />
      </Suspense>
      <Suspense>
        <WhyChooseUs />
      </Suspense>
      <Suspense>
        <PriceList />
      </Suspense>
      <Suspense>
        <ContactUs />
      </Suspense>
      <div className="h-72"></div>
    </main>
  )
}
