import { Suspense } from "react";
import Image from "next/image";
import Link from "next/link";

import {
  IcArrowRight,
  ImageThumbnailVideo,
} from '@/public/images'
import {BackgroundHeader, CourseHeader, CourseDetail} from "./_components";


export const metadata = {
  title: 'Course Detail',
  // description: 'Generated by create next app',
}

export default function CourseVideo() {

  return (
    <div className="relative w-screen top-0 left-0">

      <Suspense>
        <BackgroundHeader />
      </Suspense>

      <div className="flex-col space-y-6 lg:space-y-12 w-full min-h-screen items-center mx-auto lg:px-20 lg:py-20 2xl:py-24 z-50">
        <Suspense>
          <CourseHeader />
        </Suspense>

        <Suspense>
          <CourseDetail />
        </Suspense>
      </div>
    </div>
  )
}
