'use client'
import { Suspense } from "react";
import Image from "next/image";

import {
  ImageThumbnailVideo,
} from '@/public/images'
import {CourseHeader, CourseDetail} from "./_components";

export const metadata = {
  title: 'Course Detail',
  description: 'Generated by create next app',
}

export default function CourseVideo() {


  return (
    <div className="relative w-screen top-0 left-0">
      <Suspense>
        <div className="absolute top-0 left-0 w-screen -z-10">
          <Image src={ImageThumbnailVideo}
                 layout="responsive" objectFit='cover'
                 className="w-screen absolute background-blur bg-opacity-40"
                 alt="thumbnail-course"  />
          <div className="w-screen background-radial bg-opacity-90"></div>
          <div style={{top:"50vh" ,height:"1000vh"}} className="absolute w-screen bg-black"></div>
        </div>
        <div className="circle-green -z-10"></div>
        <div className="circle-red -z-10"></div>
      </Suspense>


      <div className="flex-col space-y-12 w-full min-h-screen items-center mx-auto 2xl:px-20 2xl:py-24 z-50">
        <Suspense>
          <CourseHeader />
        </Suspense>

        <Suspense>
          <CourseDetail />
        </Suspense>
      </div>
    </div>
  )
}
