import {
  SearchNews,
  LastestNews,
  FeaturedNews,
  TopPicks
} from './_components'
import {Suspense} from "react";

export const metadata = {
  title: 'News - WEALPY',
  description: 'Generated by create next app',
}

export default function News() {


  return (
    <main className="flex-col w-full min-h-screen items-center mx-auto 2xl:px-20 2xl:py-24">
      <div className="flex flex-col gap-2 min-h-screen pt-20 2xl:pt-20">

        <Suspense>
          <SearchNews />
        </Suspense>


        <div className="flex flex-row h-4/5 gap-4 2xl:px-20">
          <Suspense>
            <div className="w-1/3 flex flex-col gap-2">
              <div className="font-semibold text-white text-xl 2xl:px-16">Featured News</div>
              <FeaturedNews />
            </div>
          </Suspense>

          <Suspense>
            <div className="w-1/3 relative flex flex-col gap-2  ">
              <div className="font-semibold text-white text-xl">Lastest News</div>
              <div className="relative h-full overflow-y-scroll scrollbar-none rounded-t-3xl">
                <div className="absolute w-full h-auto ">
                  <div className="w-full h-full flex flex-col gap-4 ">
                    <LastestNews />
                  </div>
                </div>
              </div>
            </div>
          </Suspense>

          <Suspense>
            <div className="w-1/3 flex flex-col gap-2 2xl:pr-12">
              <div className="font-semibold text-white text-xl">5 Top Picks</div>
              <div className="w-full h-full flex flex-col gap-2">
                <TopPicks />
              </div>
            </div>
          </Suspense>
        </div>
      </div>
    </main>
  )
}
