name: Deploy to Cloud Run from Source

on:
  push:
    branches:
      - main
      - develop
      
env:
  PROJECT_ID: wealpy-390315 # TODO: update Google Cloud project id
  SERVICE_PRODUCTION: production-nextjs-wealpy
  SERVICE_DEVELOPMENT: development-nextjs-wealpy
  REGION_PRODUCTION: asia-southeast1  # TODO: update Cloud Run service region
  REGION_DEVELOPMENT: asia-southeast1
  
jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2


#       NOTE: Alternative option - authentication via credentials json
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      - name: Determine Environment
        id: determine_env
        run: echo "::set-output name=env::${{ github.ref == 'refs/heads/develop' && 'DEVELOPMENT' || 'PRODUCTION' }}"

      - name: Deploy to Cloud Run (Development)
        id: deploy_dev
        if: steps.determine_env.outputs.env == 'DEVELOPMENT'
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE_DEVELOPMENT }}
          region: ${{ env.REGION_DEVELOPMENT }}
          # NOTE: If required, update to the appropriate source folder
          source: ./
      
      - name: Deploy to Cloud Run (Production)
        id: deploy_prod
        if: steps.determine_env.outputs.env == 'PRODUCTION'
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE_PRODUCTION }}
          region: ${{ env.REGION_PRODUCTION }}
          # NOTE: If required, update to the appropriate source folder
          source: ./
      
      # If required, use the Cloud Run URL output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy_dev.outputs.url || steps.deploy_prod.outputs.url }}
